<a href="https://colab.research.google.com/github/priya25-art/Machine-Learning/blob/main/Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [9]:
df.sample(5)

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
1,102,IT,62,45.0,5,2,Male,Fail
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail
0,101,CSE,85,78.0,12,0,Female,Pass
2,103,CSE,91,88.0,15,0,Female,Pass


In [46]:
X = df.drop("Final_Result",axis=1)

In [47]:
X

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender
0,101,CSE,85,78.0,12,0,Female
1,102,IT,62,45.0,5,2,Male
2,103,CSE,91,88.0,15,0,Female
3,104,ECE,74,62.5,8,1,Male
4,105,IT,55,39.0,4,3,Female


In [43]:
y=df["Final_Result"]

In [48]:
y

,Final_Result
0,Pass
1,Fail
2,Pass
3,Pass
4,Fail


In [27]:
df.isnull()


,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False


In [28]:
df.isnull().sum()

,0
Student_ID,0
Department,0
Attendance,0
Internal_Marks,1
Study_Hours,0
Backlogs,0
Gender,0
Final_Result,0


In [29]:
df.isnull().count()


,0
Student_ID,5
Department,5
Attendance,5
Internal_Marks,5
Study_Hours,5
Backlogs,5
Gender,5
Final_Result,5


Median Amputation

In [40]:
df["Internal_Marks"].fillna(df["Internal_Marks"].mean())


,Internal_Marks
0,78.0
1,45.0
2,88.0
3,62.5
4,39.0


In [41]:
df["Internal_Marks"]

,Internal_Marks
0,78.0
1,45.0
2,88.0
3,62.5
4,39.0


In [49]:
df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,62.5,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail


In [50]:
Y=df["Final_Result"]

In [51]:
y

,Final_Result
0,Pass
1,Fail
2,Pass
3,Pass
4,Fail


In [58]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [60]:
encoder.fit_transform(df["Gender"])
np.array([0,1,0,1,0])

array([0, 1, 0, 1, 0])

In [64]:
encoder.fit_transform(df["Department"])
np.array([0,2,0,1,2])

array([0, 2, 0, 1, 2])

In [65]:
df["Department"]

,Department
0,CSE
1,IT
2,CSE
3,ECE
4,IT


In [66]:
pd.get_dummies(df,columns =["Department"])

,Student_ID,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Department_CSE,Department_ECE,Department_IT
0,101,85,78.0,12,0,Female,Pass,True,False,False
1,102,62,45.0,5,2,Male,Fail,False,False,True
2,103,91,88.0,15,0,Female,Pass,True,False,False
3,104,74,62.5,8,1,Male,Pass,False,True,False
4,105,55,39.0,4,3,Female,Fail,False,False,True


Min max scaler Normalization


In [69]:
scaler=MinMaxScaler()
scaler.fit_transform(df[["Study_Hours"]])

array([[0.72727273],
       [0.09090909],
       [1.        ],
       [0.36363636],
       [0.        ]])

In [75]:
scaler = MinMaxScaler()
df["Study_Hours_scaled"] = scaler.fit_transform(df[["Study_Hours"]])
print(df.columns)
df[["Study_Hours", "Study_Hours_scaled"]]

Index(['Student_ID', 'Department', 'Attendance', 'Internal_Marks',
       'Study_Hours', 'Backlogs', 'Gender', 'Final_Result',
       'Study_Hours_scaled'],
      dtype='object')


,Study_Hours,Study_Hours_scaled
0,12,0.727273
1,5,0.090909
2,15,1.000000
3,8,0.363636
4,4,0.000000


Standardization

In [78]:
std_scaler=StandardScaler()
std_scaler.fit_transform(df[["Study_Hours"]])

array([[ 0.76802458],
       [-0.91202919],
       [ 1.48804762],
       [-0.19200614],
       [-1.15203687]])